[package]
name = "raylib-bindings"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

[lib]
name = "raylib"
path = "src/lib.rs"

[dependencies]
bitflags = "2.4.2"
float-cmp = "0.9.0"
half = "2.4.0"
rusttype = "0.9.3"
va_list = "0.1.4"
